export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SUPER_ASSISTANT: 'SUPER_ASSISTANT', 
  SUPER_COMMERCIAL: 'SUPER_COMMERCIAL',
  SUPER_FINANCE: 'SUPER_FINANCE',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  COMPANY_OPERATOR: 'COMPANY_OPERATOR', 
  CLIENT_ADMIN: 'CLIENT_ADMIN',
  CLIENT_LOGISTICS: 'CLIENT_LOGISTICS',
  INDEPENDENT_DRIVER: 'INDEPENDENT_DRIVER'
} as const;

export const DEMAND_STATUS = {
  DRAFT: 'BROUILLON',
  PENDING: 'EN_ATTENTE',
  CONFIRMED: 'CONFIRMEE',
  IN_PROGRESS: 'EN_COURS',
  COMPLETED: 'TERMINEE',
  CANCELLED: 'ANNULEE'
} as const;